
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ProductContextProvider from "@/context/products/products.context";
import TopBar from "@/components/TopBar/TopBar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased portal-layout`}
      >
        <ProductContextProvider>
         <TopBar/>
          <main className="pt-16">
            {children}
          </main>
        </ProductContextProvider>
      </body>
    </html>
  );
}
